### ISSUE TITLE
Some (configurable) sorting of VM listing would be handy

### ISSUE THREAD

**Issue by philclifford** [marxjohnson/quickemu_gui#1]
Being able to sort the list of existing VMs by name or date (or size ...) would be helpful. (And the current ordering seems to be somewhat arbitrary )
![ordering](https://user-images.githubusercontent.com/8797027/136881479-9672105e-dd28-4816-9255-ad67f0360381.png)

**Comment by marxjohnson** [comment]
I have just pushed a0058ec to sort the list alphabetically, which is a start.
