### ISSUE TITLE
Merge with quickgui

### ISSUE THREAD

**Issue by marxjohnson** [marxjohnson/quickemu_gui#15]
@ymauray and I have decided to combine forces by merging quickemu_gui into [quickgui](https://github.com/quickgui/quickgui/).
The "Manager" screen will be added to quickgui, while quickgui's existing download interface will replace quickemu_gui's.

I will refactor the code so it's easier to include. Once the merge is complete, I will close this project. Future issues can be raised against quickgui.

**Comment by philclifford** [comment]
... or could be if issues were turned on in that repo :smiling_imp: :point_up:

**Comment by marxjohnson** [comment]
Merge complete, the new project can be found at https://github.com/quickgui/quickgui/
