### ISSUE TITLE
Possible option for chosing display when running and capturing the run output

### ISSUE THREAD

**Issue by philclifford** [marxjohnson/quickemu_gui#3]
Would be nice to be able to select/tick to add e.g. " --display spice" to the run, and awesome to capture/parse the output to re-present links to e.g. connect with spicy or ssh .... i.e. a running VM you've started could have buttons for those as well as stop.

**Comment by marxjohnson** [comment]
There's now a button next to the "Run" button to enable/disable SPICE. When you launch, it should automatically open the spicy client.
